<!DOCTYPE html>
<html lang="es"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.24">

  <meta name="author" content="Rubén Rodríguez Fernández (@rrunix)">
  <meta name="dcterms.date" content="2026-10-09">
  <title>Capa de Transporte</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-ed81c1eb8156b6dfccbd5cf511d4619a.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <meta name="mermaid-theme" content="default">
  <script src="site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="theme_images/background_fronpage.png" data-background-position="center 70%" data-background-size="33%" class="quarto-title-block center">
  <h1 class="title">Capa de Transporte</h1>
  <p class="subtitle">Comunicación lógica entre procesos de aplicación</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Rubén Rodríguez Fernández (@rrunix) 
</div>
</div>
</div>

  <p class="date">2026-10-09</p>
</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Tabla de contenidos</h2>
<ul>
<li><a href="#/introducción" id="/toc-introducción">Introducción</a></li>
<li><a href="#/funciones-principales" id="/toc-funciones-principales">Funciones Principales</a></li>
<li><a href="#/udp-user-datagram-protocol" id="/toc-udp-user-datagram-protocol">UDP (User Datagram Protocol)</a></li>
<li><a href="#/tcp-transmission-control-protocol" id="/toc-tcp-transmission-control-protocol">TCP (Transmission Control Protocol)</a></li>
<li><a href="#/comparativa-tcp-vs-udp-para-videojuegos" id="/toc-comparativa-tcp-vs-udp-para-videojuegos">Comparativa TCP vs UDP para Videojuegos</a></li>
<li><a href="#/resumen" id="/toc-resumen">Resumen</a></li>
</ul>
</nav>
</section>
<section>
<section id="introducción" class="title-slide slide level1 center">
<h1>Introducción</h1>

</section>
<section id="qué-es-la-capa-de-transporte" class="slide level2">
<h2>¿Qué es la Capa de Transporte?</h2>
<blockquote>
<p>La capa de transporte proporciona comunicación lógica entre procesos de aplicación que se ejecutan en diferentes hosts</p>
</blockquote>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Función principal:</strong></p>
<ul>
<li>Se ejecuta en hosts finales</li>
<li>No en el núcleo de la red</li>
<li>Divide mensajes en segmentos</li>
<li>Recompone segmentos en el receptor</li>
</ul>
<p><strong>Protocolos principales:</strong></p>
<ul>
<li><strong>UDP</strong>: Protocolo minimalista</li>
<li><strong>TCP</strong>: Protocolo complejo con garantías</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="width: 12vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">block-beta
    columns 1
    
    A["&lt;b&gt;Capa de Aplicación&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;HTTP, HTTPS, FTP, SMTP&lt;br/&gt;DNS, DHCP, Telnet, SSH"]
    
    B["&lt;b&gt;Capa de Transporte&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;TCP, UDP&lt;br/&gt;Control de flujo y errores"]
    
    C["&lt;b&gt;Capa de Internet&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;IP, ICMP, ARP&lt;br/&gt;Enrutamiento, Direccionamiento"]
    
    D["&lt;b&gt;Capa de Acceso a la Red&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;Ethernet, WiFi, PPP&lt;br/&gt;Frames, MAC Address&lt;br/&gt;Control de acceso al medio"]
    
    classDef highlight fill:#ff9999,stroke:#cc0000,stroke-width:4px,color:#000
    classDef normal fill:#e1f5fe,stroke:#0277bd,stroke-width:2px,color:#000
    
    class B highlight
    class A,C,D normal
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
</div></div>
</section>
<section id="ejemplo-cliente-servidor-con-udp" class="slide level2">
<h2>Ejemplo: Cliente-Servidor con UDP</h2>
<div style="width: 50vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-height="4" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant A as Client A
    participant I as The Internet
    participant B as Server B
        
    A-&gt;&gt;I: Paquete UDP 1 (IP destino: 8.8.8.8, puerto: 80)
    I-&gt;&gt;B: Paquete 1 entregado
    
    A-&gt;&gt;I: Paquete UDP 2 (IP destino: 8.8.8.8, puerto:80)
    I-&gt;&gt;B: Paquete 2 entregado
    
    A-&gt;&gt;I: Paquete UDP 3 (IP destino: 8.8.8.8, puerto:80)
    
    A-&gt;&gt;I: Paquete UDP 4 (IP destino: 8.8.8.8, puerto:80)
    I-&gt;&gt;B: Paquete 4 entregado (llega primero!)
    A-&gt;&gt;I: Paquete UDP 5 (IP destino: 8.8.8.8, puerto:80)
    I-&gt;&gt;B: Paquete 3 entregado (llega tarde!)
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<ul>
<li>Paquete 5: perdido (~1% pérdida normal)</li>
<li>Paquete 4 llega antes que el 3</li>
<li>UDP no corrige orden ni pérdidas</li>
</ul>
</section></section>
<section>
<section id="funciones-principales" class="title-slide slide level1 center">
<h1>Funciones Principales</h1>

</section>
<section id="multiplexación-y-demultiplexación" class="slide level2">
<h2>1. Multiplexación y Demultiplexación</h2>
<p><strong>Multiplexación:</strong> Recoger información de diferentes sockets y enviarla por un único medio.</p>
<p><strong>Demultiplexación:</strong> Recibir segmentos y enviarlos a los sockets correspondientes.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Identificación de sockets:</strong></p>
<ul>
<li>TCP: (IP y Puerto origen, IP y puerto destino)</li>
<li>UDP: (<span style="color:red;">IP y puerto origen</span>, IP y puerto destino)</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Puertos:</strong> Identificadores numéricos (1-65535)</p>
<ul>
<li>Servidores: asignación manual y fija</li>
<li>Clientes: asignación aleatoria</li>
</ul>
</div></div>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    subgraph "MULTIPLEXACIÓN"
        A1[Socket 1&lt;br/&gt;App A] --&gt; M[Multiplexor&lt;br/&gt;Capa de Transporte]
        A2[Socket 2&lt;br/&gt;App B] --&gt; M
        A3[Socket 3&lt;br/&gt;App C] --&gt; M
        M --&gt; N[Red&lt;br/&gt;Medio único]
    end
    
    subgraph "DEMULTIPLEXACIÓN"
        N2[Red&lt;br/&gt;Segmentos entrantes] --&gt; D[Demultiplexor&lt;br/&gt;Capa de Transporte]
        D --&gt; B1[Socket 1&lt;br/&gt;App A]
        D --&gt; B2[Socket 2&lt;br/&gt;App B]
        D --&gt; B3[Socket 3&lt;br/&gt;App C]
    end
    
    N -.-&gt;|Transmisión| N2
    
    classDef appClass fill:#e1f5fe,stroke:#0277bd,stroke-width:2px
    classDef muxClass fill:#f3e5f5,stroke:#7b1fa2,stroke-width:2px
    classDef netClass fill:#fff3e0,stroke:#f57c00,stroke-width:2px
    
    class A1,A2,A3,B1,B2,B3 appClass
    class M,D muxClass
    class N,N2 netClass
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="transferencia-fiable" class="slide level2">
<h2>2. Transferencia Fiable</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Características de una transferencia fiable:</strong></p>
<ul>
<li>No se corrompe ningún bit</li>
<li>No se pierde información (paquetes)</li>
<li>La información se entrega en orden correcto</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Opciones de implementación:</strong></p>
<ol type="1">
<li>Usar protocolos fiables existentes (TCP)</li>
<li>Implementar características propias sobre protocolo no fiable (UDP + lógica aplicación)</li>
</ol>
</div></div>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    
    E[EMISOR] --&gt; PC1[PROTOCOLO&lt;br/&gt;CONFIABILIDAD]
    PC1 --&gt; MNF[MEDIO&lt;br/&gt;NO FIABLE&lt;br/&gt;&lt;br/&gt;• Puede corromper bits&lt;br/&gt;• Puede perder paquetes&lt;br/&gt;• Puede desordenar]
    MNF --&gt; PC2[PROTOCOLO&lt;br/&gt;CONFIABILIDAD]
    PC2 --&gt; R[RECEPTOR]
    
    PC1 -.-&gt;|Implementa| MECH[• Detección de errores&lt;br/&gt;• Retransmisión&lt;br/&gt;• Control de flujo&lt;br/&gt;• Secuenciación&lt;br/&gt;• ACK/NACK&lt;br/&gt;• Timeouts]
    PC2 -.-&gt;|Implementa| MECH
    
    classDef endpointClass fill:#e3f2fd,stroke:#1976d2,stroke-width:2px
    classDef protocolClass fill:#e8f5e8,stroke:#2e7d32,stroke-width:2px
    classDef unreliableClass fill:#ffebee,stroke:#d32f2f,stroke-width:2px
    classDef reliableClass fill:#f3e5f5,stroke:#7b1fa2,stroke-width:2px
    classDef mechClass fill:#fafafa,stroke:#616161,stroke-width:1px
    
    class E,R endpointClass
    class PC1,PC2 protocolClass
    class MNF unreliableClass
    class MECH mechClass
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="otros-conceptos" class="slide level2">
<h2>Otros conceptos</h2>
<ul>
<li><strong>Control de flujo</strong>: Evita que el emisor sature al receptor limitando la velocidad de envío según la capacidad del destinatario</li>
<li><strong>Control de congestión</strong>: Ajusta la velocidad de transmisión para evitar saturar la red cuando detecta congestión</li>
<li><strong>Temporización</strong>: Proporciona el tiempo mínimo de entrega de datos entre emisor y receptor a través de la red</li>
<li><strong>Tasa de transferencia mínima</strong>: Garantiza una velocidad mínima de transmisión de datos para aplicaciones que requieren ancho de banda constante</li>
</ul>
</section></section>
<section>
<section id="udp-user-datagram-protocol" class="title-slide slide level1 center">
<h1>UDP (User Datagram Protocol)</h1>

</section>
<section id="características-de-udp" class="slide level2">
<h2>Características de UDP</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Protocolo minimalista [RFC 768]:</strong></p>
<ul>
<li>Basado en best-effort</li>
<li>No orientado a conexión</li>
<li>Entrega no fiable y sin orden</li>
<li>Integridad básica (checksum)</li>
<li>Multiplexación y demultiplexación</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Lo que NO proporciona:</strong></p>
<ul>
<li>Control de flujo</li>
<li>Control de congestión</li>
<li>Temporización</li>
<li>Tasa de transferencia mínima</li>
<li>Seguridad</li>
</ul>
</div></div>
<div class="fragment">
<p><strong>“Fire-and-forget”:</strong> Envías el paquete y te olvidas, independientemente de si llega</p>
</div>
</section>
<section id="estructura-del-paquete-udp" class="slide level2">
<h2>Estructura del Paquete UDP</h2>
<div class="cell" data-reveal="true" data-fig-height="6" data-out-width="80%" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">packet-beta

    0-15: "Source Port"
    16-31: "Destination Port"
    32-47: "Length"
    48-63: "Checksum"
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li><strong>Longitud:</strong> Hasta 65535 bytes (limitado por MTU)</li>
<li><strong>Checksum:</strong> Verificación de integridad</li>
<li>Estructura simple comparada con otros protocolos</li>
</ul>
</section>
<section id="checksum-udp" class="slide level2">
<h2>Checksum UDP</h2>
<p><strong>Proceso de cálculo:</strong></p>
<ol type="1">
<li>Preparación: pseudo-cabecera IP + cabecera UDP + datos</li>
<li>División en palabras de 16 bits</li>
<li>Suma usando aritmética de complemento a uno</li>
<li>Complemento del resultado → campo checksum</li>
</ol>
<p><strong>Verificación en receptor:</strong></p>
<ul>
<li>Mismo algoritmo incluyendo checksum recibido</li>
<li>Resultado esperado: 0xFFFF</li>
<li>Si difiere: datagrama descartado silenciosamente</li>
</ul>
</section>
<section id="casos-de-uso-de-udp" class="slide level2">
<h2>Casos de Uso de UDP</h2>
<p><strong>Aplicaciones ideales para UDP:</strong></p>
<ul>
<li><strong>Multimedia streaming:</strong> Tolerante a pérdidas, sensible a interrupciones</li>
<li><strong>DNS:</strong> Respuestas rápidas necesarias</li>
<li><strong>SNMP:</strong> Administración de red</li>
<li><strong>Gaming online:</strong> Latencia baja crítica</li>
<li><strong>QUIC/HTTP3:</strong> Base para protocolos modernos optimizados</li>
</ul>
<p>Ejemplo: Implementar protocolo propio sobre UDP para juegos</p>
<ul>
<li>Añadir número de paquete</li>
<li>Descartar paquetes fuera de orden</li>
<li>Ignorar duplicados</li>
<li>Sobrecarga mínima</li>
</ul>
</section></section>
<section>
<section id="tcp-transmission-control-protocol" class="title-slide slide level1 center">
<h1>TCP (Transmission Control Protocol)</h1>

</section>
<section id="características-de-tcp" class="slide level2">
<h2>Características de TCP</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Protocolo confiable [RFC 793]:</strong></p>
<ul>
<li>Orientado a conexión</li>
<li>Entrega fiable y ordenada</li>
<li>Control de flujo</li>
<li>Control de congestión</li>
<li>Multiplexación y demultiplexación</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Lo que NO proporciona:</strong></p>
<ul>
<li>Temporización específica</li>
<li>Tasa mínima garantizada</li>
<li>Seguridad nativa (necesita TLS/SSL)</li>
</ul>
</div></div>
<p><strong>Trade-off:</strong> Confiabilidad y orden sobre velocidad pura</p>
</section>
<section id="estructura-del-paquete-tcp" class="slide level2">
<h2>Estructura del Paquete TCP</h2>
<div style="width: 50vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-height="6" data-out-width="80%" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">packet-beta
  0-15: "Source Port"
  16-31: "Destination Port"
  32-63: "Sequence Number"
  64-95: "Acknowledgment Number"
  96-99: "Data Offset"
  100-105: "Reserved"
  106: "URG"
  107: "ACK"
  108: "PSH"
  109: "RST"
  110: "SYN"
  111: "FIN"
  112-127: "Window"
  128-143: "Checksum"
  144-159: "Urgent Pointer"
  160-191: "Options (variable)"
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<ul>
<li><strong>Sequence number</strong>: Número que identifica la posición del primer byte de datos en el segmento dentro del flujo de datos.</li>
<li><strong>Ack number</strong>: Indica el próximo número de secuencia que el receptor espera recibir. Confirma la recepción correcta de datos anteriores.</li>
<li><strong>Window:</strong> Implementa control de flujo (bytes que receptor acepta)</li>
</ul>
</section>
<section id="mecanismos-de-confiabilidad" class="slide level2">
<h2>Mecanismos de Confiabilidad</h2>
<blockquote>
<p>Los mecanismos de confiabilidad en TCP garantizan que los datos lleguen correctamente y en orden.</p>
</blockquote>
<p><strong>Números de secuencia y ACKs:</strong></p>
<ul>
<li>Cada byte tiene número único</li>
<li>Cuando enviamos información, está identificada por un número de secuencia (SEQ)</li>
<li>Además, esperamos confirmación de que se ha recibido correctamente (ACK)</li>
<li>ACKs acumulativos (ACK para byte N confirma hasta N-1)</li>
<li>Los ACKs y SEQs permite detectar datos perdidos, duplicados o desordenados</li>
</ul>
<p><strong>Detección de pérdidas:</strong></p>
<ul>
<li>Detección de timeout</li>
<li>Detección de ACKs duplicados</li>
</ul>
</section>
<section id="tcp-básico" class="slide level2">
<h2>TCP básico</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div style="width: 38vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant E as Emisor
    participant R as Receptor
    
    Note over E,R: Conexión ya establecida, seq inicial=100
    
    E-&gt;&gt;R: seq=100, data="Hola" (4 bytes)
    Note over R: Recibe
    R-&gt;&gt;E: ACK=104 ("Espero byte 104")
    Note over R: Confirma
    
    E-&gt;&gt;R: seq=104, data=" mundo!" (7 bytes)  
    R-&gt;&gt;E: ACK=111 ("Espero byte 111")
    
    E-&gt;&gt;R: seq=111, data=" TCP" (4 bytes)
    E-&gt;&gt;R: seq=115, data=" rocks" (6 bytes)
    Note over R: Recibe ambos correctamente
    Note over R: ACK acumulativo confirma todo
    R-&gt;&gt;E: ACK=121 ("Recibí todo hasta byte 120")
    
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Primer envío: seq=100 con “Hola” (4 bytes) → el receptor responde ACK=104, indicando que espera el byte 104</li>
<li>Envíos consecutivos: Cada mensaje usa el número de secuencia donde terminó el anterior (104, 111, 115)</li>
<li>ACK acumulativo final: ACK=121 confirma de una vez ambos paquetes “TCP” y “rocks”</li>
</ul>
</div></div>
</section>
<section id="detección-de-pérdidas" class="slide level2">
<h2>Detección de pérdidas</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="pérdidas-por-timeout">Pérdidas por timeout</h3>
<div style="width: 38vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-width="6" data-fig-height="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant E as Emisor
    participant R as Receptor
    E -&gt;&gt; X: seq=100, data="A", Paquete perdido
    Note over E: Timeout de seq:100, reenvio
    E -&gt;&gt; R: seq=100, data="A",
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<ul>
<li>Si no recibe ACK en tiempo determinado → asume pérdida y retransmite</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="pérdidas-por-acks-duplicados">Pérdidas por ACKs duplicados</h3>
<div style="width: 38vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-width="6" data-fig-height="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant E as Emisor
    participant R as Receptor
    E -&gt;&gt; X: seq=100, data="A", Paquete perdido
    E -&gt;&gt; R: seq=101, data="B"
    E -&gt;&gt; R: seq=102, data="C"
    E -&gt;&gt; R: seq=103, data="D"
    R -&gt;&gt; E: ACK=100
    R -&gt;&gt; E: ACK=100
    R -&gt;&gt; E: ACK=100
    Note over E,R: Retransmisión rápida
    E -&gt;&gt; R: seq=100, data="A"
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<ul>
<li>3 ACKs duplicados → Fast Retransmit inmediato</li>
</ul>
</div></div>
</section>
<section id="control-de-flujo" class="slide level2">
<h2>Control de Flujo</h2>
<blockquote>
<p>El control de flujo en TCP es un mecanismo que evita que el emisor envíe más datos de los que el receptor puede procesar.</p>
</blockquote>
<div class="columns">
<div class="column" style="width:50%;">
<div style="width: 30vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-height="4" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant E as Emisor
    participant R as Receptor
    
    Note over R: Buffer: 4KB libres
    R-&gt;&gt;E: ACK=1000, Window=4096
    E-&gt;&gt;R: seq=1000, data=2KB
    Note over R: Buffer: 2KB libres
    R-&gt;&gt;E: ACK=3000, Window=2048
    E-&gt;&gt;R: seq=3000, data=2KB
    Note over R: Buffer: 0KB libres (lleno)
    R-&gt;&gt;E: ACK=5000, Window=0
    Note over E: Detiene envío, inicia probe timer
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Receptor informa de su capacidad disponible, y se define:</li>
<li><code>VentanaRecepcion = BufferRecepcion - (UltimoByteRecibido - UltimoByteLeido)</code></li>
<li>El emisor se limita a esta ventana</li>
<li>Si la capacidad es 0, se espera un tiempo y se vuelve a probar.</li>
</ul>
</div></div>
</section>
<section id="control-de-congestión" class="slide level2">
<h2>Control de Congestión</h2>
<blockquote>
<p>El control de congestión en TCP es un mecanismo que ajusta automáticamente la velocidad de envío (ventana de congestión) para evitar saturar la red cuando detecta pérdida de paquetes o retardos.</p>
</blockquote>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="ventana-de-congestión">Ventana de congestión</h3>
<ul>
<li>Variable del emisor</li>
<li>Bytes máximos en “el aire” (enviados sin ACK)</li>
<li>Tasa efectiva = min(VentanaCongestion, VentanaRecepcion)</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="eventos-de-congestión-pérdidas">Eventos de Congestión (Pérdidas)</h3>
<ul>
<li><p><strong>Timeout -&gt; Modo slow start</strong></p>
<ul>
<li>Pérdida severa</li>
<li>Ventana → 1 MSS</li>
</ul></li>
<li><p><strong>3 ACKs duplicados -&gt; Modo congestion avoidance</strong></p>
<ul>
<li>Pérdida moderada</li>
<li>Ventana → mitad</li>
</ul></li>
</ul>
</div></div>
</section>
<section id="mecanismos-de-control-de-congestión" class="slide level2">
<h2>Mecanismos de control de congestión</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="slow-start">Slow start</h3>
<div style="width: 30vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-height="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant E as Emisor
    participant R as Receptor
    
    Note over E: Slow Start: cwnd=1 MSS
    E-&gt;&gt;R: seq=1000, MSS=1KB
    R-&gt;&gt;E: ACK=2000
    Note over E: cwnd=2 MSS
    E-&gt;&gt;R: seq=2000, MSS=1KB
    E-&gt;&gt;R: seq=3000, MSS=1KB
    R-&gt;&gt;E: ACK=4000
    Note over E: cwnd=4 MSS (crecimiento exponencial)
    Note over E: ... continúa hasta threshold o detectar pérdida ...
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<p>Duplicar ventana por cada RTT</p>
</div><div class="column" style="width:50%;">
<h3 id="congestion-avoidance">Congestion Avoidance</h3>
<div style="width: 30vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-height="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant E as Emisor
    participant R as Receptor
    
    Note over E: Congestion Avoidance: cwnd=1 MSS

    E-&gt;&gt;R: seq=1000, MSS=1KB
    R-&gt;&gt;E: ACK=2000

    Note over E: cwnd=2 MSS

    E-&gt;&gt;R: seq=2000, MSS=1KB
    E-&gt;&gt;R: seq=3000, MSS=1KB
    R-&gt;&gt;E: ACK=4000

    Note over E: cwnd=3 MSS (crecimiento lineal)
    Note over E: ... continúa hasta detectar pérdida ...
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
<p>Incrementar en 1 la ventana en cada RTT</p>
</div></div>
</section>
<section id="handshake-de-tres-fases" class="slide level2">
<h2>Handshake de Tres Fases</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div style="width: 38vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-height="4" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant CS as Cliente Socket
    participant SS as Server Socket (listen)
    participant NS as Nuevo Socket
    
    Note over CS: Estado: CLOSED
    Note over SS: Estado: LISTEN
    CS-&gt;&gt;SS: SYN=1, seq=x
    Note over CS: Estado: SYN_SENT
    Note over SS: accept() crea nuevo socket
    SS-&gt;&gt;NS: Deriva conexión
    Note over NS: Estado: SYN_RCVD
    NS-&gt;&gt;CS: SYN=1, ACK=1, seq=y, ack=x+1
    Note over CS: Estado: ESTABLISHED
    CS-&gt;&gt;NS: ACK=1, seq=x+1, ack=y+1
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Se negocian: MSS, opciones de ventana, extensiones TCP</li>
<li>Los flags de las cabeceras también consumen bits.</li>
<li>El serverSocket está en el servidor,</li>
<li>una vez se establece la comunicación ambos sockets son iguales.</li>
</ul>
</div></div>
</section>
<section id="terminación-de-conexión" class="slide level2">
<h2>Terminación de Conexión</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div style="width: 28vw; text-align: center; margin: 0 auto;">
<div class="cell" data-reveal="true" data-fig-height="4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant C as Cliente
    participant S as Servidor
    
    Note over C,S: Conexión establecida
    C-&gt;&gt;S: FIN=1, seq=x
    Note over C: Estado: FIN_WAIT_1
    S-&gt;&gt;C: ACK=1, ack=x+1
    Note over C: Estado: FIN_WAIT_2
    S-&gt;&gt;C: FIN=1, ACK=1, seq=y
    Note over S: Estado: LAST_ACK
    C-&gt;&gt;S: ACK=1, ack=y+1
    Note over C: Estado: TIME_WAIT
    Note over C: Espera 2*MSL
    Note over C,S: CLOSED
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Cada extremo debe enviar su propio FIN y recibir confirmación, permitiendo cierre unidireccional (half-close).</li>
<li>El cliente espera 2*MSL para asegurar que su último ACK llegó y manejar retransmisiones tardías antes del cierre definitivo.</li>
</ul>
</div></div>
</section>
<section id="equidad-y-coexistencia" class="slide level2">
<h2>Equidad y Coexistencia</h2>
<p><strong>TCP es “fair”:</strong></p>
<ul>
<li>N conexiones TCP comparten enlace equitativamente</li>
<li>Cada una obtiene ~R/N del ancho de banda R</li>
</ul>
<p><strong>Limitaciones:</strong></p>
<ul>
<li>UDP no implementa control → puede monopolizar</li>
<li>Aplicaciones con múltiples conexiones TCP</li>
<li>Conexiones con menor RTT tienen ventaja</li>
</ul>
</section></section>
<section>
<section id="comparativa-tcp-vs-udp-para-videojuegos" class="title-slide slide level1 center">
<h1>Comparativa TCP vs UDP para Videojuegos</h1>

</section>
<section id="cuándo-usar" class="slide level2">
<h2>Cuándo usar…</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="udp">UDP</h3>
<p><strong>Requisitos para UDP:</strong></p>
<ul>
<li>Latencias &lt; 50ms</li>
<li>Actualizaciones frecuentes</li>
<li>Información nueva más valiosa que la vieja</li>
</ul>
<p><strong>Ventajas:</strong></p>
<ul>
<li>Cabeceras pequeñas</li>
<li>Sin tráfico de control</li>
<li>Servidor necesita menos recursos</li>
<li>No mantiene estado</li>
</ul>
<p><strong>Ejemplos:</strong> Shooters (Counter Strike), juegos de lucha</p>
</div><div class="column" style="width:50%;">
<h3 id="tcp">TCP</h3>
<p><strong>Requisitos para TCP:</strong></p>
<ul>
<li>Tolerancia 100-200ms latencia</li>
<li>Entrega ordenada garantizada</li>
<li>Detección y corrección de errores</li>
</ul>
<p><br> <strong>Consideraciones:</strong></p>
<ul>
<li>Bloqueo cabeza de línea</li>
<li>Latencias variables por retransmisiones</li>
<li>Mayor tráfico de red</li>
</ul>
<p><br> <strong>Ejemplos:</strong> MMORPGs (World of Warcraft), juegos por turnos</p>
</div></div>
</section>
<section id="ejemplos-concretos" class="slide level2">
<h2>Ejemplos Concretos</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>World of Warcraft (TCP):</strong></p>
<ul>
<li>Hechizos necesitan entrega garantizada</li>
<li>Actualizaciones de inventario críticas</li>
<li>Estado de misiones consistente</li>
<li>MMORPGs toleran 100-200ms</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Counter Strike (UDP):</strong></p>
<ul>
<li>Retroalimentación inmediata crítica</li>
<li>Actualizaciones posición/disparos</li>
<li>Técnicas de interpolación en cliente</li>
<li>Mitiga efecto paquetes perdidos</li>
</ul>
</div></div>
</section></section>
<section>
<section id="resumen" class="title-slide slide level1 center">
<h1>Resumen</h1>

</section>
<section id="puntos-clave" class="slide level2">
<h2>Puntos Clave</h2>
<ul>
<li class="fragment">La capa de transporte proporciona comunicación lógica entre <strong>procesos</strong></li>
<li class="fragment"><strong>UDP:</strong> Minimalista, best-effort, no orientado a conexión</li>
<li class="fragment"><strong>TCP:</strong> Confiable, ordenado, orientado a conexión</li>
<li class="fragment"><strong>Multiplexación:</strong> Múltiples sockets por un medio</li>
<li class="fragment"><strong>Control de flujo:</strong> Evita saturar al receptor</li>
<li class="fragment"><strong>Control de congestión:</strong> Responde a condiciones de red</li>
<li class="fragment"><strong>Trade-off fundamental:</strong> Confiabilidad vs velocidad</li>
<li class="fragment">Elección protocolo depende de requisitos aplicación</li>
</ul>


<div class="reveal-header">
<div class="header-title">
<p> </p>
</div>
<div class="header-logo">
<img data-src="">
</div>
</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="theme_images/URJClogo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'pdfMaxPagesPerSlide': 1,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"openSlideNumber":false,"openOnInit":false,"keyboard":false,"titleSelector":"","width":"third"},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.15,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    // Override Quarto's Mermaid responsive behavior to prevent pagination
    window.addEventListener('load', function() {
      // Wait for Quarto's mermaid initialization to complete
      setTimeout(function() {
        // Override the makeResponsive function to do nothing
        if (window._quartoMermaid) {
          window._quartoMermaid.makeResponsive = function(svg) {
            // Do nothing - prevent responsive behavior that causes pagination
          };
          
          // Override setSvgSize to not restrict sizes
          window._quartoMermaid.setSvgSize = function(svg) {
            // Remove any size restrictions
            svg.style.maxWidth = 'none';
            svg.style.maxHeight = 'none';
            svg.style.width = 'auto';
            svg.style.height = 'auto';
            
            // Force the slide section to allow overflow for this diagram
            const section = svg.closest('section');
            if (section) {
              section.style.overflow = 'visible';
              section.style.height = 'auto';
              section.style.minHeight = '100vh';
            }
            
            // Force parent containers to allow full height
            let parent = svg.parentElement;
            while (parent && !parent.classList.contains('reveal')) {
              parent.style.maxHeight = 'none';
              parent.style.height = 'auto';
              parent.style.overflow = 'visible';
              parent = parent.parentElement;
            }
          };
          
          // Reprocess all existing mermaid diagrams
          const mermaidSvgs = document.querySelectorAll('svg.mermaid-js');
          mermaidSvgs.forEach(svg => {
            svg.style.maxWidth = 'none';
            svg.style.maxHeight = 'none';
            svg.style.width = 'auto';
            svg.style.height = 'auto';
            
            // Remove any width/height attributes that might cause pagination
            svg.removeAttribute('width');
            svg.removeAttribute('height');
            
            // Force containers to allow full height
            const section = svg.closest('section');
            if (section) {
              section.style.overflow = 'visible';
              section.style.height = 'auto';
              section.style.minHeight = '100vh';
            }
            
            let parent = svg.parentElement;
            while (parent && !parent.classList.contains('reveal')) {
              parent.style.maxHeight = 'none';
              parent.style.height = 'auto';
              parent.style.overflow = 'visible';
              parent = parent.parentElement;
            }
          });
        }
      }, 1000);
    }, false);
    </script>

    <style>
    /* Additional CSS to ensure Mermaid diagrams are not restricted */
    .mermaid, .mermaid svg, svg.mermaid-js {
      max-width: none !important;
      max-height: none !important;
      width: auto !important;
      height: auto !important;
      overflow: visible !important;
    }

    /* Ensure containers don't restrict Mermaid */
    .cell-output-display .mermaid,
    .reveal .slides section .mermaid {
      max-width: none !important;
      max-height: none !important;
      overflow: visible !important;
    }

    /* Force sections with Mermaid to allow overflow and full height */
    .reveal .slides section:has(.mermaid),
    .reveal .slides section:has(svg.mermaid-js) {
      overflow: visible !important;
      height: auto !important;
      min-height: 100vh !important;
    }

    /* Remove height restrictions from all parent containers of Mermaid */
    .reveal .slides section .cell-output-display:has(.mermaid),
    .reveal .slides section .cell-output-display:has(svg.mermaid-js),
    .reveal .slides section .cell:has(.mermaid),
    .reveal .slides section .cell:has(svg.mermaid-js) {
      max-height: none !important;
      height: auto !important;
      overflow: visible !important;
    }

    /* Ensure the reveal slides container itself doesn't restrict height */
    .reveal .slides {
      overflow: visible !important;
    }
    </style>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/rrunix\.github\.io\/jer_slides\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

<script src="site_libs/quarto-contrib/metropolis-beamer-1.0.0/add_header.js" defer="true"></script>
</body></html>